name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Build the app
      run: npm install
    - name: Run integration tests 
      run: npm test
